### ISSUE TITLE
[Feat] 숙소 예약 요금 계산 API 구현

### ISSUE THREAD

**Issue by who-hoo** [ak2j38/airbnb#53]
- [x] 비즈니스 요구사항 분석, 필요한 정책들과 정책별 요금 산정 방법 정하기
    - ex) 평일 요금정책 - 기본요금의 100%,  주말 요금정책 - 기본요금의 130%
- [x] 정해진 요금정책 내용을 구현체로 구현하기
    - [x] 스테이 기간을 평일/주말 일수로 나누기
        - ex) 2022/06/01(수) ~ 2022/06/06(월) -> (5박 6일) 평일 : 3일(수, 목, 일) 주말 : 2일(금, 토)
- [x] RoomRepository 구현 - `findById`
- [x] ReservationService - 요금 계산 서비스 구현
- [x] 테스트코드 작성..ㅎㅎ 
- [x] ReservationController - 찐서비스로 갈아끼우기

**Comment by ak2j38** [comment]
완 료 우
